version: "3.9"
services:
  webdex-app:
    build: .
    ports:
      - "3000:3000"
    links:
      - webdex-database
  webdex-database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=webdex
    volumes:
      - webdex-data:/var/lib/mysql
volumes:
  webdex-data: